add go1.17 static analysis
Signed-off-by: Jonas Galvão Xavier <jonas.agx@gmail.com>

diff --git a/.github/workflows/validations.yaml b/.github/workflows/validations.yaml
--- a/.github/workflows/validations.yaml
+++ b/.github/workflows/validations.yaml
@@ -11,6 +11,52 @@ env:
   GO_STABLE_VERSION: true
 
 jobs:
+  // TODO: please delete me once once we move to 1.18 and golangci-lint works with it.
+  Static-Analysis-Golangci-lint:
+    # Note: changing this job name requires making the same update in the .github/workflows/release.yaml pipeline
+    name: "Static analysis against 1.17"
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/setup-go@v2
+        with:
+          go-version: "1.17"
+          stable: ${{ env.GO_STABLE_VERSION }}
+
+      - uses: actions/checkout@v2
+
+      - name: Restore tool cache
+        id: tool-cache
+        uses: actions/cache@v2.1.3
+        with:
+          path: ${{ github.workspace }}/.tmp
+          key: ${{ runner.os }}-tool-${{ hashFiles('Makefile') }}
+
+      - name: Restore go cache
+        id: go-cache
+        uses: actions/cache@v2.1.3
+        with:
+          path: ~/go/pkg/mod
+          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-go-${{ env.GO_VERSION }}-
+
+      - name: (cache-miss) Bootstrap all project dependencies
+        if: steps.tool-cache.outputs.cache-hit != 'true' || steps.go-cache.outputs.cache-hit != 'true'
+        run: make bootstrap
+
+      - name: Bootstrap CI environment dependencies
+        run: make ci-bootstrap
+
+      - name: Run linters
+        run: make lint
+
+      # allow for PRs to skip validating the syft version to allow for incremental updates of syft before release.
+      # In this way checks against the main branch (which are required for release) will fail, but PR checks will not
+      - name: Ensure syft version is a release version
+        run: |
+          echo "GitHub reference: ${GITHUB_REF##*/}"
+          git fetch origin main
+          git merge-base --is-ancestor ${GITHUB_REF##*/} origin/main && make validate-syft-release-version || echo "skipping syft version checkk"
 
   Static-Analysis:
     # Note: changing this job name requires making the same update in the .github/workflows/release.yaml pipeline
